import { StyleSheet } from 'react-native';

import { bg, border, red, text, text2 } from '@/constants/colors';

/** 매물 상세 화면 StyleSheet — [id].tsx 전용 */
export const detailStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F4F6F9' },
  pageScrollContent: { flexGrow: 1 },
  container: { width: '100%', alignSelf: 'center' },
  notFound: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16 },
  notFoundBack: { color: '#1D4ED8', fontSize: 16, fontWeight: '600' },
  notFoundText: { color: '#334155', fontSize: 16 },
  header: { backgroundColor: bg, gap: 8 },
  headerTopRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  backBtn: { padding: 4, marginLeft: -4 },
  badgeRow: { flexDirection: 'row', gap: 8 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  badgeText: { fontSize: 12, fontWeight: '700' },
  headerTitle: { color: text, fontWeight: '800', marginTop: 4 },
  headerAddr: { color: text2, fontSize: 13 },
  headerBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 2, gap: 10 },
  headerBottomNarrow: { flexDirection: 'column', alignItems: 'flex-start' },
  headerPrice: { fontSize: 20, fontWeight: '800', color: text },
  headerBtnGroup: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  headerBtnGroupNarrow: { width: '100%', justifyContent: 'flex-start' },
  headerBtn: { borderWidth: 1, borderColor: border, borderRadius: 6, paddingHorizontal: 9, paddingVertical: 5 },
  headerBtnText: { color: text, fontSize: 12, fontWeight: '600' },
  headerBtnDel: { color: red },
  infoRow: { flexDirection: 'column', alignItems: 'stretch', paddingVertical: 16, gap: 12 },
  infoRowWide: { width: '100%' },
  infoRowColumn: { flexDirection: 'column' },
  carouselUltraWide: { width: '100%', alignSelf: 'stretch' },
  specGrid: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  specGridFull: { width: '100%' },
  specGridFlex: { minWidth: 0, flex: 1 },
  specGridUltra: { minWidth: 0 },
  specCellUltra2col: {
    width: '50%',
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 8,
    justifyContent: 'flex-start',
  },
  specRow: { flexDirection: 'row', flex: 1 },
  specRowBottom: { borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  specCell: {
    flex: 1,
    paddingTop: 12,
paddingBottom: 20,
paddingHorizontal: 6,
    justifyContent: 'flex-start',
    gap: 2,
    minWidth: 0,
  },
  specCellRight: { borderRightWidth: 1, borderRightColor: '#F1F5F9' },
  specLabel: { fontSize: 11, color: '#94A3B8', fontWeight: '500', marginBottom: 4 },
  specValue: { fontSize: 12, fontWeight: '700', color: '#1E293B', flexWrap: 'wrap' },
  memoBox: {
    minHeight: 60,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'column',
  },
  memoBoxUltra: { minWidth: 0 },
  memoBoxFlex: { minWidth: 0, flex: 1 },
  memoBoxFull: { width: '100%' },
  memoBody: { paddingBottom: 8 },
  memoLabel: { fontSize: 11, color: '#94A3B8', fontWeight: '600', marginBottom: 8 },
  memoText: { fontSize: 14, color: '#334155', lineHeight: 22 },
});