import { StyleSheet } from 'react-native';

/** 매물 등록 화면 전용 스타일 */
export const registerStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F0F4FF' },
  scrollContent: { padding: 16, paddingBottom: 40, gap: 14 },
  title: { fontSize: 20, fontWeight: '800', color: '#111827' },
  sub: { fontSize: 13, color: '#6B7585', marginTop: 4 },
  section: { backgroundColor: '#F8FAFF', borderRadius: 12, padding: 14, gap: 10, borderWidth: 1, borderColor: '#E2E8F0' },
  sectionLabel: { fontSize: 13, fontWeight: '700', color: '#334155' },
  rowChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1.5, borderColor: '#D8DCE6', backgroundColor: '#F8FAFF' },
  chipOn: { borderColor: '#1A56DB', backgroundColor: '#EEF3FD' },
  chipTxt: { fontSize: 13, fontWeight: '600', color: '#475569' },
  chipTxtOn: { color: '#1A56DB' },
  input: {
    borderWidth: 1,
    borderColor: '#D8DCE6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#18202E',
    backgroundColor: '#F8FAFF',
  },
  inputMultiline: { minHeight: 100, textAlignVertical: 'top' },
  voiceBtn: { backgroundColor: '#1A56DB', borderRadius: 10, paddingVertical: 14, alignItems: 'center' },
  voiceBtnBusy: { backgroundColor: '#94A3B8' },
  voiceBtnTxt: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  suggestBox: { borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 8, overflow: 'hidden', marginTop: 4 },
  suggestRow: { paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  suggestTxt: { fontSize: 14, color: '#1E293B' },
  saveBtn: { backgroundColor: '#0F172A', borderRadius: 12, paddingVertical: 16, alignItems: 'center', marginTop: 8 },
  saveBtnTxt: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  backRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  backTxt: { fontSize: 15, color: '#1A56DB', fontWeight: '700' },
  hint: { fontSize: 12, color: '#94A3B8' },
  relationPickerBtn: {
    alignSelf: 'flex-start',
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginBottom: 2,
    backgroundColor: 'transparent',
  },
  relationPickerBtnTxt: { fontSize: 13, fontWeight: '700', color: '#334155' },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    padding: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: '#F8FAFF',
    borderRadius: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748B',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  modalOptionRow: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  modalOptionTxt: { fontSize: 16, fontWeight: '600', color: '#1E293B' },
});